app/models/__init__.py
from .models import app_queries

app/models/models.py
app_queries = {
    "create_db": '''CREATE DATABASE IF NOT EXISTS brainstem;''',
    "create_table_user":
        '''
        CREATE TABLE IF NOT EXISTS brainstem.users (
            uuid VARCHAR(36) PRIMARY KEY,
            username VARCHAR(50) NOT NULL,
            email VARCHAR(100) NOT NULL
        );
        ''',
    "create_user": '''INSERT INTO brainstem.users (uuid, username, email) VALUES (?,?,?);''',
    "read_user": '''SELECT * from brainstem.users WHERE uuid = ?;''',
    "update_user": '''UPDATE brainstem.users SET username = ?, email = ? WHERE uuid = ?;''',
    "delete_user": '''DELETE FROM brainstem.users WHERE uuid = ?;''',
}

app/__init__.py
from .app import createApp, doDB

app/app.py
import flask
import dotenv
import os

from .views import views
from config import configuration


def createApp(this_conf='standard'):
    app = flask.Flask(__name__)
    # app = flask.Flask(__name__, static_url_path="/app/static", static_folder='static')

    # app.config.from_object(configuration[this_conf])

    # # Change path to the desired configuration file:
    # app.static_url_path = app.config.get('STATIC_FOLDER')
    # app.static_folder = app.root_path + app.static_url_path

    dotenv.load_dotenv()
    config = {
        'host': os.getenv("DB_HOST"),
        'port': int(os.getenv("DB_PORT")),
        'user': os.getenv("DB_USER"),
        'password': os.getenv("DB_PASS"),
        'ssl': 1
    }

    app.register_blueprint(views)
    return app


def doDB():
    print("Doing db initiation.")

app/views/__init__.py
from .router import views

app/views/router.py
import flask


views = flask.Blueprint("views", __name__)


@views.route("/")
def landing():
    return flask.render_template("landing.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
    
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <!-- Custom CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/app.css') }}"
    />

    <title>{% block title %} {% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('views.landing')}}">Home</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Page 2</a>
            <a class="nav-link" href="#">Page 3</a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="container">{% block main %} {% endblock %}</main>
  </body>
</html>

app/templates/landing.html
{% extends 'base.html' %} {% block title %} Landing! {% endblock %} {% block
main %}

<p>
  Spicy jalapeno bacon ipsum dolor amet pork spare ribs picanha, chuck filet
  mignon jerky cupim corned beef t-bone. Alcatra sausage tail meatball sirloin
  pork belly tongue chicken ground round hamburger drumstick strip steak chislic
  ham hock frankfurter. Meatball venison pork pastrami brisket shoulder sausage
  picanha. Shoulder sausage pork belly fatback cow chicken bacon doner pig
  frankfurter pastrami tenderloin porchetta burgdoggen. Pork loin fatback
  brisket kielbasa. Landjaeger flank drumstick, doner turducken kevin ground
  round sausage ham hock burgdoggen. Swine salami ribeye, beef jerky pork loin
  frankfurter tongue alcatra ham hock ham. Rump burgdoggen prosciutto shoulder
  short loin alcatra ball tip tail kevin, pork loin bacon pig doner boudin.
  Shoulder landjaeger corned beef frankfurter bacon burgdoggen ham beef.
  Andouille alcatra shank drumstick doner salami turkey bresaola filet mignon
  frankfurter chicken. Swine salami ham hock cow pork beef. Beef tongue picanha,
  pork belly alcatra cupim biltong tenderloin hamburger drumstick. Tongue swine
  rump pork loin meatloaf doner. Picanha jerky sirloin meatball ribeye ball tip.
  Ground round biltong rump t-bone tail ham. Chicken corned beef t-bone boudin
  jerky shankle landjaeger ball tip fatback ham bacon prosciutto drumstick.
  Fatback corned beef venison ribeye kielbasa pork chop. Beef ribs andouille
  tenderloin beef tongue bresaola jerky frankfurter shankle chuck drumstick.
  Porchetta tongue ribeye leberkas filet mignon chislic turkey brisket doner
  frankfurter. Pork chop boudin swine capicola hamburger shoulder pork sausage
  short loin bresaola cow turkey andouille. Pig meatball sirloin prosciutto
  strip steak boudin rump. Swine beef ribs meatloaf strip steak burgdoggen pork
  pastrami t-bone biltong tail brisket meatball. Sausage short ribs brisket
  andouille turducken leberkas burgdoggen. Spare ribs landjaeger pork loin,
  boudin ham hock pancetta burgdoggen picanha kevin pastrami hamburger.
  Tenderloin shankle shoulder rump boudin chuck meatloaf ground round. Pastrami
  buffalo tongue tail venison tenderloin strip steak tri-tip pork belly chuck
  frankfurter. Spare ribs ball tip tenderloin, chislic turducken biltong shank
  shoulder jowl t-bone drumstick tri-tip.
</p>
{% endblock %}